module.exports = {
  GROUPS_RECEIVED: "GROUPS_RECEIVED",
  GROUP_RECEIVED: "GROUP_RECEIVED",
  GROUP_REMOVE: "GROUP_REMOVE",
  USERS_GROUP_RECEIVED: "USERS_GROUP_RECEIVED",
  USERS_GROUPS_RECEIVED: "USERS_GROUPS_RECEIVED",
  USERS_GROUP_REMOVE: "USERS_GROUP_REMOVE"
};
