require 'date'
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
users = User.create([
  { name: "Joni", email: "joni@email.com", password: "password", img_url: "1253_user1299_090713-072140_i1b7hs.jpg" },
  { name: "James", email: "james@email.com", password: "password", img_url: "james-taylor2_htus9b.jpg" },
  { name: "Kanye", email: "kanye@email.com", password: "password", img_url: "45a3532e-a454-4590-be0a-002de1a0c652_tfwhix.jpg"},
  { name: "Beck", email: "beck@email.com", password: "password", img_url: "beck-624-1367411586_oxebxm.jpg" },
  { name: "David", email: "david@email.com", password: "password", img_url: "original_david_bowie_3_600xfree_a2ecjq.jpg" },
  { name: "Matt", email: "matt@email.com", password: "password", img_url: "matt_street_zxlkmk.jpg" },
  { name: "Fez", email: "fez@email.com", password: "password", img_url: "Fez__That__70s_Show_ny5e90.jpg" },
  { name: "Galadriel", email: "galadriel@email.com", password: "password", img_url: "tumblr_m7or4oGxXe1qgfscco1_500_ze6n8z.jpg" },
  { name: "Erykah", email: "erykah@email.com", password: "password", img_url: "tumblr_ng0781ral21tmnjwco1_400_iu1cw9" },
  { name: "Guest", email: "guest@email.com", password: "password", img_url: "22266877342_d7c8a36ba7_m_icplzt.jpg" },
  { name: "Sheri", email: "sheri@email.com", password: "password", img_url: "10792946_pa2t1c.jpg" },
  { name: "Wilfred", email: "wilfred@email.com", password: "password", img_url: "23947837641_e5456f1850_m_voo3vr.jpg" },
  { name: "Charlie", email: "charlie@email.com", password: "password", img_url: "dayman_fwltjq.jpg"}
  ])

  groups = Group.create([
    { title: "Naturalists", body: "We are outdoorsy folks who revel in the beauty of hills, fields, & forests.", location: "Northern California", organizer_id: users.first.id, img_url: "2409473_ce363ce06a_z_krvofh.jpg" },
    { title: "Crafts", body: "We are very fond of DIY projects.", location: "San Francisco", organizer_id: users.last.id, img_url: "281183_647db85d53_z_nd57il.jpg" },
    { title: "Visual Art", body: "Artists who delve into all spaces & fear no mediums", location: "San Francisco", organizer_id: users[4].id, img_url: "tumblr_mzjxs6u9Le1qgfmj0o1_1280_xrfz7e.jpg" },
    { title: "Crossword Club", body: "Sip tea, crossword, repeat.", location: "San Francisco", organizer_id: users[11].id, img_url: "tumblr_lxd99fX4DP1r6rtf4o1_500_g6mvt8.jpg" },
    { title: "Wanderers", body: "Always on the move.", location: "Anywhere but Here", organizer_id: users[1].id, img_url: "tumblr_nm92r4dUvU1rti241o1_1280_g5hwrv.jpg" },
    { title: "Music is Life", body: "Follow the beat.", location: "SF", organizer_id: users[2].id, img_url: "17403792278_1f76646ee0_z_mccbfw.jpg" },
    ])

Event.create([
  { title: "Mushroom Foraging", body: "Hike and spot the various mushroom species!", location: "Muir Woods", date: DateTime.new(2016,1,8,9,0), group_id: groups.first.id, organizer_id: users.first.id, img_url: "21508192309_c2304bff19_z_tuddmy.jpg"},
  { title: "Sunset Walk", body: "Take in the crisp, salty air on this 5 mile walk.", location: "Bolinas", date: DateTime.new(2016,1,9,17,0), group_id: groups.first.id, organizer_id: users.first.id, img_url: "21473947675_dcaca3b781_z_s0rxkv.jpg"},
  { title: "Pots for Planting", body: "Throw clay for the perfect pot", location: "Ceramic Studio on Castro", date: DateTime.new(2016,1,10,12,0), group_id: groups[1].id, organizer_id: users.last.id, img_url: "tumblr_men7huHU7j1r6furjo1_1280_cts1qn.jpg"},
  { title: "Mad Hatter", body: "Making the wildest of hats to wear on our Un-Birthdays!", location: "Wilfred's House", date: DateTime.new(2016,1,11,14,0), group_id: groups[1].id, organizer_id: users.last.id, img_url: "167764_ba17eee87c_z_kirooi.jpg"},
  { title: "Painting", body: "Paint it up - drip style like Pollack or finger style like when you were 5", location: "Downtown Studio", date: DateTime.new(2016,1,12,16,0), group_id: groups[2].id, organizer_id: users[4].id, img_url: "tumblr_o0b82hxi2v1qa6y0bo1_540_cmgn7y.jpg"},
  { title: "Late Afternoon Photography", body: "Taking it way outdoors to capture nature's essence", location: "Pacifica", date: DateTime.new(2016,1,13,16,0), group_id: groups[2].id, organizer_id: users[4].id, img_url: "21493898355_067b2e4d90_z_msv7gz.jpg"},
  { title: "SF Chronicle's Crossword", body: "Can't wait to open up that the morning paper with y'all.", location: "Philz", date: DateTime.new(2016,1,14,9,0), group_id: groups[3].id, organizer_id: users[11].id, img_url: "tumblr_lfdifaZuX31qd32e5o1_540_oceczw.jpg"},  { title: "P", body: "If it's too windy, smack your coffee mug ontop of that loose corner.", location: "The Sidewalk Cafe", date: DateTime.new(2016,1,14,9,0), group_id: groups[3].id, organizer_id: users[11].id, img_url: "tumblr_lfdifaZuX31qd32e5o1_540_oceczw.jpg"},
  { title: "Oakland Tribune's X-Word", body: "If it's too windy, slap your coffee mug on that loose corner.", location: "The Sidewalk Cafe", date: DateTime.new(2016,1,15,9,0), group_id: groups[3].id, organizer_id: users[11].id, img_url: "tumblr_nmpd0alFSh1qa11wdo1_1280_nsofga.jpg"},
  { title: "Bus to Pacifica", body: "Share bus ride playlists with eachother. See you bright & early. Bring snacks.", location: "Bus Depot", date: DateTime.new(2016,1,16,7,0), group_id: groups[4].id, organizer_id: users[1].id, img_url: "tumblr_n1eus8sWdN1ts2owco1_1280_atfn7p.jpg"},
  { title: "Onwards to Seattle", body: "Let's road trip to Seattle! Bring good food, vibes, and music.", location: "SF->Seattle", date: DateTime.new(2016,1,17,8,0), group_id: groups[4].id, organizer_id: users[1].id, img_url: "21470549373_3e30a878f4_z_u7gxjs.jpg"},
  { title: "Show in the Tenderloin", body: "Get ready to dance and fill your ears with great acoustics.", location: "TL", date: DateTime.new(2016,1,18,20,0), group_id: groups[5].id, organizer_id: users[2].id, img_url: "tumblr_nii5qtOMlq1r6a3q3o1_1280_hb4fej.jpg"},
  ])

  UsersGroup.create([
    { user_id: users[0].id, group_id: groups[0].id },
    { user_id: users[0].id, group_id: groups[1].id },
    { user_id: users[0].id, group_id: groups[2].id },
    { user_id: users[0].id, group_id: groups[4].id },
    { user_id: users[0].id, group_id: groups[5].id },
    { user_id: users[1].id, group_id: groups[0].id },
    { user_id: users[1].id, group_id: groups[2].id },
    { user_id: users[1].id, group_id: groups[4].id },
    { user_id: users[1].id, group_id: groups[5].id },
    { user_id: users[2].id, group_id: groups[1].id },
    { user_id: users[2].id, group_id: groups[2].id },
    { user_id: users[2].id, group_id: groups[3].id },
    { user_id: users[2].id, group_id: groups[5].id },
    { user_id: users[3].id, group_id: groups[0].id },
    { user_id: users[3].id, group_id: groups[2].id },
    { user_id: users[3].id, group_id: groups[3].id },
    { user_id: users[3].id, group_id: groups[4].id },
    { user_id: users[3].id, group_id: groups[5].id },
    { user_id: users[4].id, group_id: groups[1].id },
    { user_id: users[4].id, group_id: groups[2].id },
    { user_id: users[4].id, group_id: groups[4].id },
    { user_id: users[4].id, group_id: groups[5].id },
    { user_id: users[5].id, group_id: groups[0].id },
    { user_id: users[5].id, group_id: groups[1].id },
    { user_id: users[5].id, group_id: groups[2].id },
    { user_id: users[5].id, group_id: groups[3].id },
    { user_id: users[5].id, group_id: groups[4].id },
    { user_id: users[5].id, group_id: groups[5].id },
    { user_id: users[6].id, group_id: groups[0].id },
    { user_id: users[6].id, group_id: groups[1].id },
    { user_id: users[6].id, group_id: groups[2].id },
    { user_id: users[6].id, group_id: groups[3].id },
    { user_id: users[6].id, group_id: groups[4].id },
    { user_id: users[6].id, group_id: groups[5].id },
    { user_id: users[7].id, group_id: groups[0].id },
    { user_id: users[7].id, group_id: groups[1].id },
    { user_id: users[7].id, group_id: groups[2].id },
    { user_id: users[7].id, group_id: groups[3].id },
    { user_id: users[7].id, group_id: groups[5].id },
    { user_id: users[8].id, group_id: groups[2].id },
    { user_id: users[8].id, group_id: groups[3].id },
    { user_id: users[8].id, group_id: groups[5].id },
    { user_id: users[9].id, group_id: groups[1].id },
    { user_id: users[9].id, group_id: groups[3].id },
    { user_id: users[9].id, group_id: groups[5].id },
    { user_id: users[10].id, group_id: groups[0].id },
    { user_id: users[10].id, group_id: groups[1].id },
    { user_id: users[10].id, group_id: groups[2].id },
    { user_id: users[10].id, group_id: groups[3].id },
    { user_id: users[10].id, group_id: groups[4].id },
    { user_id: users[10].id, group_id: groups[5].id },
    { user_id: users[11].id, group_id: groups[0].id },
    { user_id: users[11].id, group_id: groups[1].id },
    { user_id: users[11].id, group_id: groups[2].id },
    { user_id: users[11].id, group_id: groups[3].id },
    { user_id: users[11].id, group_id: groups[4].id },
    { user_id: users[11].id, group_id: groups[5].id },
    { user_id: users[12].id, group_id: groups[0].id },
    { user_id: users[12].id, group_id: groups[1].id },
    { user_id: users[12].id, group_id: groups[2].id },
    { user_id: users[12].id, group_id: groups[3].id },
    { user_id: users[12].id, group_id: groups[4].id },
    { user_id: users[12].id, group_id: groups[5].id },
    ])
